### PR TITLE
added 7 CS mentioned in issue 34 into Python folder

### PR DESCRIPTION
**Pull request by Raghavi94**

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
Pls Add files in corresponding folders!

**Comment by Raghavi94** [comment]
> Pls Add files in corresponding folders!

Sure I will do

**Comment by Raghavi94** [comment]
I have updated the cheat sheets into respective folders..please check out.

**Comment by VedantKhairnar** [comment]
Thanks for your contribution! ❄️ 
Enjoy the winter! ☃️

**Comment by Raghavi94** [comment]
Thank you ☺

**Pull request merged**
