### PR TITLE
added bootstrap4,linux and git cheat sheets

### PR DESCRIPTION
**Pull request by gupta31**

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
Is this for DWOC?

**Comment by gupta31** [comment]
Yes

**Comment by VedantKhairnar** [comment]
We need min 5 cheatsheets for DWOC

**Comment by gupta31** [comment]
Ok I will make PR with 5 cheat sheets

**Comment by VedantKhairnar** [comment]
Thanks for your contribution! ❄️ 
Enjoy the Summer! 🌞

**Pull request merged**
