### PR TITLE
Added CMD cheet sheet 

### PR DESCRIPTION
**Pull request by Amit366**
Sir I have added a Command prompt cheat sheet . Please review it .

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
For DWOC, we need min 5 cheatsheets

**Comment by Amit366** [comment]
Min 5 cheat sheet means 5 pages??

**Comment by Amit366** [comment]
Like I have given the pdf of only 2 pages so should I make it 5 pages??

**Comment by Amit366** [comment]
@VedantKhairnar sir I can upload a pdf of 65 pages.

**Comment by VedantKhairnar** [comment]
Is it a cheatsheet or book?

**Comment by Amit366** [comment]
It is a cheat sheet @VedantKhairnar

**Comment by Amit366** [comment]
Please review it and if possible merge it.

**Comment by VedantKhairnar** [comment]
Can you add that cheatsheet? Coz the present ones are less than 10 pages

**Comment by Amit366** [comment]
@VedantKhairnar sir if you want I can add a book

**Comment by Amit366** [comment]
Should I add??

**Comment by VedantKhairnar** [comment]
We need 5 cheatsheets

**Comment by Amit366** [comment]
In the pdf which I have shared it consists of all the commands A-Z.

**Comment by Amit366** [comment]
If you want then there is 64 pages pdf. I can add that

**Comment by Amit366** [comment]
@VedantKhairnar sir please merge it now

**Comment by Amit366** [comment]
@VedantKhairnar sir please review it.

**Comment by Amit366** [comment]
@VedantKhairnar is it a level 1 issue??

**Comment by VedantKhairnar** [comment]
Yeah, 5 cheatsheets is a Level-1 contribution

**Pull request merged**
