### PR TITLE
Git and github

### PR DESCRIPTION
**Pull request by vilsi12**

### CODE REVIEW

**Review by Kushal997-das — COMMENTED** [review]
Useful :)

**Comment by VedantKhairnar** [comment]
Contribution is small for DWOC Level-1

**Comment by VedantKhairnar** [comment]
Do one thing, Mention the cheatsheets you have added like
1) ABC
2) DEF
we normally need around 5 cheatsheets for DWOC Level-1 unless either of them is extraordinary

**Comment by vilsi12** [comment]
Ok

**Comment by vilsi12** [comment]
Cheat which i have done
1)Flutter
2)git and github
3)Docker
4)Ansible
5)React.md

**Comment by vilsi12** [comment]
Now @VedantKhairnar i have done

**Comment by VedantKhairnar** [comment]
Thanks for your contribution! ❄️

**Pull request merged**
