### PR TITLE
Flask

### PR DESCRIPTION
**Pull request by Ayush7614**

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
Is it for DWOC?

**Comment by Ayush7614** [comment]
Yess sir it is DWOC PLSS merge it

**Comment by Ayush7614** [comment]
@VedantKhairnar sir plss merge it

**Comment by VedantKhairnar** [comment]
Bro, for contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

**Comment by Ayush7614** [comment]
I have listed it you can review it and plss merge it

**Comment by VedantKhairnar** [comment]
Pls list them here as well. Should be 5 in number!

**Comment by Ayush7614** [comment]
1.Flask Cheet Sheet

**Comment by Ayush7614** [comment]
@VedantKhairnar sir is that ok

**Comment by VedantKhairnar** [comment]
Bro there should be minimum 5 for DWOC

**Comment by Ayush7614** [comment]
@VedantKhairnar bro now its okk so plss review it

**Comment by Ayush7614** [comment]
1.  Flask Cheat Sheet 
2.  Flask Cheat Sheet 
3.  Flask Cheat Sheet 
4.  Flask Cheat Sheet 
5.  Flask Cheat Sheet

**Comment by Ayush7614** [comment]
@VedantKhairnar sir plss review it

**Comment by Ayush7614** [comment]
@VedantKhairnar plss review it sir

**Comment by VedantKhairnar** [comment]
Sorry for the delayed response!
Thanks for your contribution! ❄️ 
Enjoy the winter ☃️

**Pull request merged**
