### PR TITLE
 Web Development/cheatsheets.md 

### PR DESCRIPTION
**Pull request by Ayush7614**

### CODE REVIEW

**Comment by Ayush7614** [comment]
1.Bootstrap Cheatsheet
2. ExpressJS Cheatsheet
3. ReactJS Cheatsheet
4. MongoDB Cheatsheet
5. Redux Cheatsheet

**Comment by Ayush7614** [comment]
@VedantKhairnar sir plss review it

**Comment by VedantKhairnar** [comment]
Only 1 PR is considered for DWOC. Is any of your previous PRs merged?

**Comment by Ayush7614** [comment]
Yess my previous PR was merged #49 this is PR

**Comment by Ayush7614** [comment]
@VedantKhairnar sir plss review it

**Pull request merged**
