### PR TITLE
PL-SQL/Numpy Cheatsheet

### PR DESCRIPTION
**Pull request by Amit0412**
Files have been added which contains the info related to PL-SQL/SUBLIME and around 100 questions related to Numpy.

### CODE REVIEW

**Comment by Amit0412** [comment]
KINDLY MERGE MY PULL REQUEST SIR.

**Comment by VedantKhairnar** [comment]
Bro Add all files in the folders corresponding to them coz all others are also cheat sheets

**Comment by Amit0412** [comment]
ok.I will.Sorry I was busy for college exams.Surely I will do it in one folder.

**Comment by VedantKhairnar** [comment]
Sure Bro. No worries! : )

**Pull request closed without merging**
