### PR TITLE
Computer Vision

### PR DESCRIPTION
**Pull request by shubhraagarwal**
This PR is with respect to issue #83. I have added a pdf file for OpenCV

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
Is this for DWOC?

**Comment by shubhraagarwal** [comment]
Yes!

**Comment by VedantKhairnar** [comment]
Atleast 5 cheatsheets are needed for DWOC

**Comment by shubhraagarwal** [comment]
Can you please elaborate?

**Comment by VedantKhairnar** [comment]
5 Cheatsheets on any topic needs to be added to proper folder for getting accepted for DWOC

**Comment by shubhraagarwal** [comment]
Okay. I will do the needful.
What level will this PR be considered for?

**Pull request closed without merging**
