### PR TITLE
Updated the Linux cheat sheet

### PR DESCRIPTION
**Pull request by devshub21**

### CODE REVIEW

**Comment by VedantKhairnar** [comment]
Is it for DWOC?

**Comment by ShubhamPatel33** [comment]
Yes for Dwoc.

**Comment by VedantKhairnar** [comment]
Bro, for contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

**Comment by ShubhamPatel33** [comment]
Ahh, gotcha

**Comment by VedantKhairnar** [comment]
Also pls quote all the cheatsheets you have added in the given format.

**Comment by VedantKhairnar** [comment]
Thanks!

**Pull request merged**
