### PR TITLE
Added Web Development Cheatsheets

### PR DESCRIPTION
**Pull request by pankaj892**

### CODE REVIEW

**Comment by Ayush7614** [comment]
I want to work on this issue plss assign me

**Comment by VedantKhairnar** [comment]
For contributing to DWOC, list all those CheatSheets you are adding[Min 5]:

Cheat Sheet 1
Cheat Sheet 2
Cheat Sheet 3
Cheat Sheet 4
Cheat Sheet 5
Nt: Only 1 PR is accepted per person for DWOC

**Comment by pankaj892** [comment]
@VedantKhairnar is there any changes i need to make to the PR ?

**Comment by VedantKhairnar** [comment]
Pls quote here all the files you are adding.

**Comment by pankaj892** [comment]
1.HTML Cheatsheet 
2.HTTP Status Codes
3.CSS Cheatsheet
4.JavaScript Cheatsheet
5.Angular Cheatsheet
6.Markdown Cheatsheet
7.NodeJS Cheatsheet
8.PHP Cheatsheet 

@VedantKhairnar is that ok

**Comment by pankaj892** [comment]
@VedantKhairnar  i see you haven't merged this PR yet is there any problem in my PR?

**Comment by VedantKhairnar** [comment]
Its Cool

**Comment by VedantKhairnar** [comment]
Thanks for your contribution! ❄️ 
Enjoy the Winter ☃️

**Pull request merged**
